REPLACE_TRIGGER_TEXT_REGEXP ~WSTAF.*~
	~Kit(LastTalkedToBy,MAGESCHOOL_GENERALIST)~ 
	~OR(9) Kit(LastTalkedToBy,QDELDSOR) 
		   Kit(LastTalkedToBy,QDCELSOR)  
		   Kit(LastTalkedToBy,QDFIESOR)  
		   Kit(LastTalkedToBy,QDSTOSOR)  
		   Kit(LastTalkedToBy,QDRBLSOR)  
		   Kit(LastTalkedToBy,QDSYLSOR)  
		   Kit(LastTalkedToBy,QDGROSOR)  
		   Kit(LastTalkedToBy,QDREVSOR)  
		   Kit(LastTalkedToBy,QDOOZSOR)~  
