// -----------------------------
// CANTRIPS by SUBTLEDOCTOR 
// -----------------------------

INCLUDE ~TomeAndBlood/data/core/tnb_kit_list.tpa~ 


ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msred.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msblu.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msgrn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msbrn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msorn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_mswhi.pro~
COPY ~TomeAndBlood/data/cantrips/spmagm02.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm03.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm04.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm05.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm06.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm07.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cant.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp420.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp710.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp809.bam~ ~override~
//COPY ~TomeAndBlood/data/cantrips/d5_wildm.2da~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cstbo.spl~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cstpn.spl~ ~override~
//Choose a cantrip
COPY ~TomeAndBlood/data/cantrips/d5_cantr.spl~ ~override~
	SAY NAME1 @6012
COPY ~TomeAndBlood/data/cantrips/d5_cant.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cant1.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cant2.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cant3.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cantr.2da~ ~override~
//abjurer cantrip: protective shell
COPY ~TomeAndBlood/data/cantrips/d5_maab.spl~ ~override~
	SAY NAME1 @6014
	SAY UNIDENTIFIED_DESC @6015
COPY ~TomeAndBlood/data/cantrips/d5_wiab.spl~ ~override~
	SAY NAME1 @6014
	SAY UNIDENTIFIED_DESC @6015
//conjurer cantrip: summon rabbit	
COPY ~TomeAndBlood/data/cantrips/d5_maco.spl~ ~override~
	SAY NAME1 @6016
	SAY UNIDENTIFIED_DESC @6017
COPY ~TomeAndBlood/data/cantrips/d5_wico.spl~ ~override~
	SAY NAME1 @6016
	SAY UNIDENTIFIED_DESC @6017
COPY ~TomeAndBlood/data/cantrips/d5_rabb.cre~ ~override~
	SAY NAME1 @6018
//diviner cantrip: anticipation
COPY ~TomeAndBlood/data/cantrips/d5_madi.spl~ ~override~
	SAY NAME1 @6019
	SAY UNIDENTIFIED_DESC @6020
COPY ~TomeAndBlood/data/cantrips/d5_widi.spl~ ~override~
	SAY NAME1 @6019
	SAY UNIDENTIFIED_DESC @6020
//enchanter cantrip: drowse
COPY ~TomeAndBlood/data/cantrips/d5_maen.spl~ ~override~
	SAY NAME1 @6021
	SAY UNIDENTIFIED_DESC @6022
COPY ~TomeAndBlood/data/cantrips/d5_wien.spl~ ~override~
	SAY NAME1 @6021
	SAY UNIDENTIFIED_DESC @6022
//illusionist cantrip: bedazzle
COPY ~TomeAndBlood/data/cantrips/d5_mail.spl~ ~override~
	SAY NAME1 @6023
	SAY UNIDENTIFIED_DESC @6024
COPY ~TomeAndBlood/data/cantrips/d5_wiil.spl~ ~override~
	SAY NAME1 @6023
	SAY UNIDENTIFIED_DESC @6024
//invoker cantrip: magic bolt
COPY ~TomeAndBlood/data/cantrips/d5_main.spl~ ~override~
	SAY NAME1 @6025
	SAY UNIDENTIFIED_DESC @6026
	WRITE_SHORT 0x098 ~%d5_msred%~
COPY ~TomeAndBlood/data/cantrips/d5_wiin.spl~ ~override~
	SAY NAME1 @6025
	SAY UNIDENTIFIED_DESC @6026
	WRITE_SHORT 0x098 ~%d5_msred%~
//necromancer cantrip: stiffen bones
COPY ~TomeAndBlood/data/cantrips/d5_mane.spl~ ~override~
	SAY NAME1 @6027
	SAY UNIDENTIFIED_DESC @6028
COPY ~TomeAndBlood/data/cantrips/d5_wine.spl~ ~override~
	SAY NAME1 @6027
	SAY UNIDENTIFIED_DESC @6028
//transmuter cantrip: earthen grasp
COPY ~TomeAndBlood/data/cantrips/d5_matr.spl~ ~override~
	SAY NAME1 @6029
	SAY UNIDENTIFIED_DESC @6030
COPY ~TomeAndBlood/data/cantrips/d5_witr.spl~ ~override~
	SAY NAME1 @6029
	SAY UNIDENTIFIED_DESC @6030
//fire bolt
COPY ~TomeAndBlood/data/cantrips/d5_mfir.spl~ ~override~
	SAY NAME1 @6031
	SAY UNIDENTIFIED_DESC @6032
COPY ~TomeAndBlood/data/cantrips/d5_wfir.spl~ ~override~
	SAY NAME1 @6031
	SAY UNIDENTIFIED_DESC @6032
	WRITE_SHORT 0x098 ~%d5_msorn%~
//ice bolt
COPY ~TomeAndBlood/data/cantrips/d5_mcld.spl~ ~override~
	SAY NAME1 @6033
	SAY UNIDENTIFIED_DESC @6034
COPY ~TomeAndBlood/data/cantrips/d5_wcld.spl~ ~override~
	SAY NAME1 @6033
	SAY UNIDENTIFIED_DESC @6034
	WRITE_SHORT 0x098 ~%d5_mswhi%~
//acid bolt
COPY ~TomeAndBlood/data/cantrips/d5_macd.spl~ ~override~
	SAY NAME1 @6035
	SAY UNIDENTIFIED_DESC @6036
COPY ~TomeAndBlood/data/cantrips/d5_wacd.spl~ ~override~
	SAY NAME1 @6035
	SAY UNIDENTIFIED_DESC @6036
	WRITE_SHORT 0x098 ~%d5_msgrn%~
//electric bolt
COPY ~TomeAndBlood/data/cantrips/d5_melc.spl~ ~override~
	SAY NAME1 @6037
	SAY UNIDENTIFIED_DESC @6038
COPY ~TomeAndBlood/data/cantrips/d5_welc.spl~ ~override~
	SAY NAME1 @6037
	SAY UNIDENTIFIED_DESC @6038
	WRITE_SHORT 0x098 ~%d5_msblu%~
//earth bolt
COPY ~TomeAndBlood/data/cantrips/d5_wert.spl~ ~override~
	SAY NAME1 @6039
	SAY UNIDENTIFIED_DESC @6040
	WRITE_SHORT 0x098 ~%d5_msbrn%~
//shield spell now protects against cantrips
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_maab~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wiab~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_maen~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wien~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_main~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wiin~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_mail~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wiil~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_mane~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wine~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_madi~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_widi~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_matr~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_witr~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_maco~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wico~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wfir~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_welc~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wcld~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wacd~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wert~ END
	BUT_ONLY 
	
//adding cantrips to appropriate mages
ACTION_PHP_EACH tnb_kit_list AS kitinfo => kitclab BEGIN 
	ACTION_IF (FILE_EXISTS_IN_GAME ~%kitclab%.2da~) BEGIN 
		APPEND ~%kitclab%.2da~ ~CANTRIPS	GA_%kitinfo_2%~
	END 
END 

//updating descriptions
	OUTER_SET strref = (0 - 1)

	COPY_EXISTING - ~clastext.2da~ ~override~
		COUNT_2DA_COLS num_cols
			READ_2DA_ENTRIES_NOW ~r2en_clastext~ num_cols
			FOR (row = 1; row < r2en_clastext; row += 1) BEGIN
				READ_2DA_ENTRY_FORMER ~r2en_clastext~ row 0 kitname
				READ_2DA_ENTRY_FORMER ~r2en_clastext~ row 4 desc
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~MAGE~) OR 
						  (~%kitname%~ STRING_EQUAL_CASE ~SORCERER~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1501
							OUTER_SPRINT new @1502
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~ABJURER~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1503
							OUTER_SPRINT new @1504
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~CONJURER~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1503
							OUTER_SPRINT new @1505
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~DIVINER~)) BEGIN
					PATCH_PRINT ~foudn diviner!~
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1503
							OUTER_SPRINT new @1506
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~ENCHANTER~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1503
							OUTER_SPRINT new @1507
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~ILLUSIONIST~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1503
							OUTER_SPRINT new @1508
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~INVOKER~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1503
							OUTER_SPRINT new @1509
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~NECROMANCER~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1503
							OUTER_SPRINT new @1510
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~TRANSMUTER~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1503
							OUTER_SPRINT new @1511
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END 
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~DRAGON_DISCIPLE~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1512
							OUTER_SPRINT new @1513
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY CASE_SENSITIVE ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				
				PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~QDMAGUS~) BEGIN
					PATCH_PRINT ~foudn magus!~
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1512
							OUTER_SPRINT new @1514
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY CASE_SENSITIVE ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~QDDDACI~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1512
							OUTER_SPRINT new @1515
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY CASE_SENSITIVE ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~QDDDCOL~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1512
							OUTER_SPRINT new @1516
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY CASE_SENSITIVE ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~QDDDELE~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1512
							OUTER_SPRINT new @1517
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY CASE_SENSITIVE ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~QDDDFIR~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1512
							OUTER_SPRINT new @1513
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY CASE_SENSITIVE ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~QDFAVSL~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1512
							OUTER_SPRINT new @1518
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY CASE_SENSITIVE ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~QDSLVSR~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1512
							OUTER_SPRINT new @1519
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY CASE_SENSITIVE ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~QDREVSR~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1512
							OUTER_SPRINT new @1520
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY CASE_SENSITIVE ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
				PATCH_IF ((~%kitname%~ STRING_EQUAL_CASE ~QDOOZSR~)) BEGIN
					INNER_ACTION  BEGIN 
						ACTION_IF (desc >= 0) BEGIN
							ACTION_GET_STRREF desc oldstring
							OUTER_SPRINT old @1512
							OUTER_SPRINT new @1521
							OUTER_PATCH_SAVE oldstring ~%oldstring%~ BEGIN
								REPLACE_TEXTUALLY CASE_SENSITIVE ~%old%~ ~%new%~
							END
							STRING_SET_EVALUATE desc ~%oldstring%~
						END 
					END
				END
			END
		 	
	