// -----------------------------
// CANTRIPS VIA WAND by SUBTLEDOCTOR 
// -----------------------------

INCLUDE ~TomeAndBlood/data/core/tnb_kit_list.tpa~ 


COPY ~TomeAndBlood/data/cantrips/d5cantw.itm~ ~override~
	SAY NAME2 @6010
	SAY IDENTIFIED_DESC @6011
COPY ~TomeAndBlood/data/cantrips/d5cantab.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5cantco.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5cantdi.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5canten.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5cantil.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5cantne.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5canttr.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_rabb.cre~ ~override~
	SAY NAME1 @6018
	WRITE_BYTE 0x270 5

//shield spell protects against cantrip wand
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 206 STR_VAR resource = ~d5cantw~ END
BUT_ONLY

COPY ~TomeAndBlood/data/core/d5_base.spl~ ~override/d5cantw1.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 122 target = 1 parameter1 = 1 timing = 9 STR_VAR resource = ~d5cantw~ END


//adding cantrips to appropriate mages
ACTION_PHP_EACH tnb_kit_list AS kitinfo => kitclab BEGIN 
	ACTION_IF (FILE_EXISTS_IN_GAME ~%kitclab%.2da~) BEGIN 
		APPEND ~%kitclab%.2da~ ~CANTRIPS	AP_D5CANTW1  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
	END 
END 


	