//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								MULTICLASS SORCERERS
//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION multiclass_sorcerers BEGIN 


INCLUDE ~tomeandblood/lib/qd_multiclass.tpa~

// TO DO:
// - what about metamagic? --> looks like it can only be done with no cost to fill... see new innate metamagic subcomponent
// - ...hmm, it's not working :(
// - ...even if it does, would still have to use the old way for mages and single-class sorcs :(
// - what about Identify?  --> looks like in cannot be done by any method

//base .2da file
//
//COPY ~tomeandblood/data/multi_sorcerers/d5sorc.2da~ ~override~

<<<<<<<< d5/d5sorc.2da
ABILITY     ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
>>>>>>>>
COPY ~d5/d5sorc.2da~ ~override/d5sorc.2da~

//__________________________________________________________________________________


ADD_KIT ~D5_FIGHTER_SORCERER~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10          	 		L S                     W   C           L   U             W I
//9     	       		A M             B L S   O   I   W       A   A             O N
//8     	       		R A             A O H   H   M   A       I   R C   S       R G
//7     	       		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6     	       		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5     	       		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4     	       		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3     	       		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2     	       		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1     	       		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_FIGHTER_SORCERER  	0 0 0 0 0 0 0 0~
~D5_FIGHTER_SORCERER    0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//  	               STR DEX CON INT WIS CHR
~D5_FIGHTER_SORCERER   0   0   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//      	           STR DEX CON INT WIS CHR
~D5_FIGHTER_SORCERER   0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//          	       STR DEX CON INT WIS CHR
~D5_FIGHTER_SORCERER   0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//              	   STR DEX CON INT WIS CHR
~D5_FIGHTER_SORCERER   0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 	  LG LN LE NG TN NE CG CN CE
~D5_FIGHTER_SORCERER  1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//      	           	FT CL MA TH DR RA
~D5_FIGHTER_SORCERER    0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~tomeandblood/data/multi_sorcerers/d5fsorc.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_FM_E K_FM_H K_FM_HE K_FM_G K_FM_D K_FM_HL K_FM_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20, FC = 8, CT = 15, CR = 18, FM = 7, CM = 14, MT = 13
~0x00004000 7~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FM0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @17051
SAY @17052
SAY @17053

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@17053)
		STR_VAR
			kit_name = D5_FIGHTER_SORCERER
			clswpbon = ~1 0 3~
			hpclass = ~HPFM~
			clsrcreq = ~1 1 1 0 0 1 0~
	END
END

ADD_KIT ~D5_SORCERER_CLERIC~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10          	 		L S                     W   C           L   U             W I
//9     	       		A M             B L S   O   I   W       A   A             O N
//8     	       		R A             A O H   H   M   A       I   R C   S       R G
//7     	       		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6     	       		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5     	       		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4     	       		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3     	       		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2     	       		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1     	       		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_SORCERER_CLERIC  	0 0 0 0 0 0 0 0~
~D5_SORCERER_CLERIC     0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//  	               STR DEX CON INT WIS CHR
~D5_SORCERER_CLERIC    0   0   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//      	           STR DEX CON INT WIS CHR
~D5_SORCERER_CLERIC    0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//          	       STR DEX CON INT WIS CHR
~D5_SORCERER_CLERIC    0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//              	   STR DEX CON INT WIS CHR
~D5_SORCERER_CLERIC    0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 	  LG LN LE NG TN NE CG CN CE
~D5_SORCERER_CLERIC   1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//      	           	FT CL MA TH DR RA
~D5_SORCERER_CLERIC     0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~tomeandblood/data/multi_sorcerers/d5csorc.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_CM_E K_CM_H K_CM_HE K_CM_G K_CM_D K_CR_HL K_CR_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20, FC = 8, CT = 15, CR = 18, FM = 7, CM = 14, MT = 13
~0x00004000 14~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CM0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @17061
SAY @17062
SAY @17063

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@17063)
		STR_VAR
			kit_name = D5_SORCERER_CLERIC
			clswpbon = ~0 0 3~
			hpclass = ~HPCM~
			clsrcreq = ~1 1 1 0 0 1 0~
	END
END

// will this work?  let's find out!
//DEFINE SPHERE ACCESS______________________________________________________________
//
ACTION_INCLUDE ~%MOD_FOLDER%/lib/fnp_compat.tpa~

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 2
	u_hammers	 		= 2
	u_maces 	 		= 2
	u_flails 			= 2
	u_axes 				= 2
	u_daggers 			= 2
	u_short_swords		= 2
	u_long_swords		= 2
	u_scimitars 		= 2
	u_katanas 			= 2
	u_bastard_swords 	= 2
	u_2hand_swords 		= 2
	u_halberds 			= 2
	u_spears 			= 2
	u_darts 			= 2
	u_slings 			= 2
	u_bows 				= 2
	u_crossbows 		= 2  
  STR_VAR
    clab_name 		= ~d5csorc~
	class 			= ~cleric_mage~
	s_Life 			= ~major~
	s_Death 		= ~minor~
	s_Benediction 	= ~major~
	s_Destruction 	= ~major~
	s_Protection 	= ~major~
	s_War 			= ~minor~
	s_Exploration   = ~minor~
	s_Knowledge 	= ~major~
	s_Deception 	= ~x~
	s_Thought 		= ~major~
	s_Dread 		= ~minor~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~major~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~minor~
	s_Perdition     = ~x~
 END

ADD_KIT ~D5_SORCERER_THIEF~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10          	 		L S                     W   C           L   U             W I
//9     	       		A M             B L S   O   I   W       A   A             O N
//8     	       		R A             A O H   H   M   A       I   R C   S       R G
//7     	       		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6     	       		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5     	       		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4     	       		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3     	       		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2     	       		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1     	       		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_SORCERER_THIEF  	0 0 0 0 0 0 0 0~
~D5_SORCERER_THIEF      0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 0 0 0 1 1 0 1 1 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//  	               STR DEX CON INT WIS CHR
~D5_SORCERER_THIEF     0   0   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//      	           STR DEX CON INT WIS CHR
~D5_SORCERER_THIEF     0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//          	       STR DEX CON INT WIS CHR
~D5_SORCERER_THIEF     0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//              	   STR DEX CON INT WIS CHR
~D5_SORCERER_THIEF     0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 	  LG LN LE NG TN NE CG CN CE
~D5_SORCERER_THIEF    0  1  1  1  1  0  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//      	           	FT CL MA TH DR RA
~D5_SORCERER_THIEF      0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~tomeandblood/data/multi_sorcerers/d5tsorc.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_MT_E K_MT_H K_MT_HE K_MT_G K_MT_D K_MT_HL K_MT_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20, FC = 8, CT = 15, CR = 18, FM = 7, CM = 14, MT = 13
~0x00004000 13~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~MT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @17071
SAY @17072
SAY @17073

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@17073)
		STR_VAR
			kit_name = D5_SORCERER_THIEF
			clswpbon = ~0 0 3~
			hpclass = ~HPMT~
			clsrcreq = ~1 1 1 0 0 1 0~
	END
END

/*
plan:
- d5ssplz# does 172 (borrow & combine from srci#), and 326 for d5slot#x
- d5slot#x triggers all EFFs according to stat values (borrow & combine from srci#)
- EFFs 171 innate clones
- innate clones cast real wiz spells???  <--- DECISION (I think, no for now)
- innate clones reduce appropriate stat
- innate clones cast d5ssplz# on 1-sec delay, where # = level

- 206 against all EFFs at chargen
- learn_spell = 321 206_spell, and 171 real_spell

- 232 from chargen
- just does 326 for refresh
- refresh does 321 on stat reductions, then casts d5ssplz on 1-sec delay
*/

//get kit identifiers_________________________________________________________________
//
OUTER_SET fighter_sorcerer_code = (0x4000 + %D5_FIGHTER_SORCERER%)
OUTER_SET sorcerer_cleric_code = (0x4000 + %D5_SORCERER_CLERIC%)
OUTER_SET sorcerer_thief_code = (0x4000 + %D5_SORCERER_THIEF%)

/*
COPY_EXISTING ~kit.ids~ ~override~
  COUNT_2DA_COLS cols 
  READ_2DA_ENTRIES_NOW rows cols 
  FOR (row = 1; row < rows; ++row) BEGIN 
    READ_2DA_ENTRY_FORMER rows row 1 ~kit_name~ 
    PATCH_IF ~%kit_name%~ STRING_EQUAL_CASE ~D5_FIGHTER_SORCERER~ BEGIN
      SET fighter_sorcerer_row = %row%
      READ_2DA_ENTRY_FORMER rows fighter_sorcerer_row 0 fighter_sorcerer_code
    END
    PATCH_IF ~%kit_name%~ STRING_EQUAL_CASE ~D5_SORCERER_CLERIC~ BEGIN
      SET sorcerer_cleric_row = %row%
      READ_2DA_ENTRY_FORMER rows sorcerer_cleric_row 0 sorcerer_cleric_code
    END
    PATCH_IF ~%kit_name%~ STRING_EQUAL_CASE ~D5_SORCERER_THIEF~ BEGIN
      SET sorcerer_thief_row = %row%
      READ_2DA_ENTRY_FORMER rows sorcerer_thief_row 0 sorcerer_thief_code
    END
  END
BUT_ONLY
*/

//add spell slot stat checks to SPLPROT_______________________________________________
//
APPEND ~splprot.2da~ ~D5_SLOTS_1_4%TAB%134%TAB%-1%TAB%7~ UNLESS ~D5_SLOTS_1_4~
APPEND ~splprot.2da~ ~D5_SLOTS_5_9%TAB%108%TAB%-1%TAB%7~ UNLESS ~D5_SLOTS_5_9~
APPEND ~splprot.2da~ ~D5_FATIGUE_IS%TAB%30%TAB%-1%TAB%1~ UNLESS ~D5_FATIGUE_IS~

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_SLOTS_1_4~ BEGIN
	  SET fake_sorc_slots_1_4 = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_SLOTS_5_9~ BEGIN
	  SET fake_sorc_slots_5_9 = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_IS~ BEGIN
	  SET fatigue_value = %row%
	END
  END
BUT_ONLY


//remove all mage spell slots_________________________________________________________
//
/* 
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d50wcst.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 0 timing = 9 END
BUT_ONLY

APPEND ~d5sorc.2da~ ~NO_CAST     AP_D50WCST  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
*/

COPY ~tomeandblood/lib/d5_base.spl~ ~override/d50wslt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 511 timing = 9 END
BUT_ONLY

APPEND ~d5sorc.2da~ ~NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~


//create advance copies of some spells________________________________________________
//
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5w206.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d50wspl.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI908~ END
  PATCH_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~16~) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~SPWI110~ END
  END
  PATCH_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~55~) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI420~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI710~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI809~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI617~ END
  END

COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot1a.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot1b.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot1c.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot1d.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot2a.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot2b.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot2c.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot2d.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot3a.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot3b.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot3c.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot3d.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot4a.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot4b.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot4c.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot4d.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot5a.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot5b.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot5c.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot5d.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot6a.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot6b.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot6c.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot6d.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot7a.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot7b.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot7c.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot7d.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot8a.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot8b.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot8c.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot8d.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot9a.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot9b.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot9c.spl~
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slot9d.spl~

COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5ssplz.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 8) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot1a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 8) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot1b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 8) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot1c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 8) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot1d~ END
//COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5ssplz2.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 12) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot2a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 12) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot2b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 12) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot2c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 12) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot2d~ END
//COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5ssplz3.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 16) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot3a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 16) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot3b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 16) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot3c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 16) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot3d~ END
//COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5ssplz4.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 20) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot4a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 20) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot4b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 20) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot4c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 20) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5slot4d~ END
//COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5ssplz5.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 8) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot5a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 8) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot5b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 8) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot5c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 8) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot5d~ END
//COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5ssplz6.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 12) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot6a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 12) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot6b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 12) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot6c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 12) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot6d~ END
//COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5ssplz7.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 16) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot7a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 16) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot7b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 16) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot7c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 16) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot7d~ END
//COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5ssplz8.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 20) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot8a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 20) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot8b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 20) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot8c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 20) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot8d~ END
//COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5ssplz9.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 24) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot9a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot9b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 24) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot9c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 24) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5slot9d~ END


//assign stats for spell slots to each spell level____________________________________
//
// level 1 = (134 << 8)
// level 2 = (134 << 12)
// level 3 = (134 << 16)
// level 4 = (134 << 20)
// level 5 = (108 << 8)
// level 6 = (108 << 12)
// level 7 = (108 << 16)
// level 8 = (108 << 20)
// level 9 = (108 << 24)
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src1a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src1%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src1%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src2a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src2%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src2%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src3a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src3%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src3%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src4a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src4%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src4%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src5a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src5%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src5%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src6a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src6%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src6%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src7a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src7%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src7%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src8a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src8%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src8%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src9a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src9%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src9%let%~ END
  END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-1.spl~ BEGIN
 COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src-1.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-2.spl~ BEGIN
 COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src-2.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-3.spl~ BEGIN
 COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src-3.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-4.spl~ BEGIN
 COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src-4.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-5.spl~ BEGIN
 COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src-5.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-6.spl~ BEGIN
 COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src-6.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-7.spl~ BEGIN
 COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src-7.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-8.spl~ BEGIN
 COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src-8.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-9.spl~ BEGIN
 COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5src-9.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 24) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END

APPEND ~d5sorc.2da~ ~SRCSLOTS    AP_D5SRC1A  AP_D5SRC1D  AP_D5SRC1E  AP_D5SRC1F  AP_D5SRC2D  AP_D5SRC2E  AP_D5SRC2F  AP_D5SRC3E  AP_D5SRC3F  AP_D5SRC4E  AP_D5SRC4F  AP_D5SRC5E  AP_D5SRC5F  AP_D5SRC6E  AP_D5SRC6F  AP_D5SRC7E  AP_D5SRC7F  AP_D5SRC8E  AP_D5SRC8F  AP_D5SRC9E  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
SRCSLOTS    AP_D5SRC1B  ****        ****        AP_D5SRC2A  ****        AP_D5SRC3A  AP_D5SRC3D  AP_D5SRC4A  AP_D5SRC4D  AP_D5SRC5A  AP_D5SRC5D  AP_D5SRC6A  AP_D5SRC6D  AP_D5SRC7A  AP_D5SRC7D  AP_D5SRC8A  AP_D5SRC8D  AP_D5SRC9A  AP_D5SRC9D  AP_D5SRC9F  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
SRCSLOTS    AP_D5SRC1C  ****        ****        AP_D5SRC2B  ****        AP_D5SRC3B  ****        AP_D5SRC4B  ****        AP_D5SRC5B  ****        AP_D5SRC6B  ****        AP_D5SRC7B  ****        AP_D5SRC8B  ****        AP_D5SRC9B  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
SRCSLOTS    ****        ****        ****        AP_D5SRC2C  ****        AP_D5SRC3C  ****        AP_D5SRC4C  ****        AP_D5SRC5C  ****        AP_D5SRC6C  ****        AP_D5SRC7C  ****        AP_D5SRC8C  ****        AP_D5SRC9V  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~


/* no need to do this, use Aquadrizzt's
COPY_EXISTING ~SPLSRCKN.2da~ ~override/d5splskn.2da~ //save a copy of the existing sorcerer spell progression 
*/

/*
//set up spell learn UI screens_______________________________________________________
//
INCLUDE ~tomeandblood/lib/sequencer_menu.tpa~

LAF CREATE_SEQUENCER_MENU 
  INT_VAR 
	name = RESOLVE_STR_REF (~Spell Selection~)
	tip = RESOLVE_STR_REF (~Spell Selection~)
	desc = RESOLVE_STR_REF (~This ability allows you to learn new spells~)
	class = 1
	maxlevel = 9
	exclude = 0x00004000 
  STR_VAR 
	spelltable = ~QD_SPLSRCKN~
	resref = ~d5msorc~
	icon = ~spcl919b~
	title = ~Spell Selection~
	label = ~Select a spell to learn~
	subspell = ~M~
END
*/

//clone arcane spells_________________________________________________________________
//
<<<<<<<< d5/d5wclons.2da
2DA V1.0 
SPLRES
		206		LEARN		EFF		INNATE	DISPLAY
>>>>>>>> 
COPY ~d5/d5wclons.2da~ ~override/d5wclons.2da~ 

<<<<<<<<  d5/d5msorc.2da
2DA V1.0
****
            	     ResRef   Type>>>>>>>>
COPY ~d5/d5msorc.2da~ ~override/d5msorc.2da~

COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
 PATCH_IF FILE_EXISTS_IN_GAME ~%SOURCE_RES%.spl~ BEGIN
//  SNPRINT 4 spell_prefix ~%SOURCE_RES%~
  READ_SHORT 0x1c spell_type 
  READ_BYTE 0x25 spell_school
  READ_LONG 0x34 spell_level
  PATCH_IF (~%SOURCE_RES%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Ww][Ii][1-9][0-5][0-9]~ = 0) && (spell_type = 1) && !(spell_school = 10) && !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI908~) && !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI124~) BEGIN
	SNPRINT (0 - 3) spell_num ~%SOURCE_RES%~
	SET go = 1
	PATCH_IF (~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI420~) || (~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI710~) || (~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI809~) || (~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI617~) BEGIN
	  PATCH_IF NOT (MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~55~) BEGIN
		SET go = 0
	  END
	END	
/*
	PATCH_IF (~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI110~) || (~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI710~) || (~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI809~) || (~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI617~) BEGIN
	  PATCH_IF NOT (MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~16~) BEGIN
		SET go = 0
	  END
	END	
*/
	PATCH_IF (go = 1) && !(FILE_CONTAINS_EVALUATED (~hidespl.2da~ ~%SOURCE_RES%~)) BEGIN
	  SPRINT ~spell_res~ ~%SOURCE_RES%~
	  READ_STRREF NAME1 spell_name
	  READ_STRREF UNIDENTIFIED_DESC spell_description
	  READ_ASCII 0x3a spell_icon
//	  LPF NAME_NUM_OF_SPELL_RES STR_VAR spell_res = EVAL ~%SOURCE_RES%~ RET spell_name spell_num END
	  PATCH_IF (FILE_CONTAINS_EVALUATED (~spell.ids~ ~2%spell_num%~)) BEGIN
		INNER_PATCH_SAVE 206_spell ~%SOURCE_RES%~ BEGIN
		  REPLACE_TEXTUALLY ~^[Ss][Pp][Ww][Ii]~ ~d5w6~
		END
		INNER_PATCH_SAVE learn_spell ~%SOURCE_RES%~ BEGIN
//		  REPLACE_TEXTUALLY ~^[Ss][Pp][Ww][Ii]~ ~d5wx~
		  REPLACE_TEXTUALLY ~%spell_res%~ ~%spell_res%M~
		END
		INNER_PATCH_SAVE spell_eff ~%SOURCE_RES%~ BEGIN
		  REPLACE_TEXTUALLY ~^[Ss][Pp][Ww][Ii]~ ~D5WV~
		END
//		TO_UPPER ~%spell_eff%~
		INNER_PATCH_SAVE innate_spell ~%SOURCE_RES%~ BEGIN
		  REPLACE_TEXTUALLY ~^[Ss][Pp][Ww][Ii]~ ~d5w4~
		END
		TEXT_SPRINT real_spell ~%SOURCE_RES%~
		INNER_ACTION BEGIN
		  APPEND ~d5wclons.2da~ ~%SOURCE_RES%	%206_spell%	%learn_spell%	%spell_eff%	%innate_spell%	%real_spell% ~
		  APPEND ~d5msorc.2da~ ~sorcerer	%SOURCE_RES%	3~
// make innates with cloned spell effects
		  ACTION_IF NOT FILE_EXISTS_IN_GAME ~%innate_spell%.spl~ BEGIN
			COPY_EXISTING ~%SOURCE_RES%.spl~ ~override/%innate_spell%.spl~
			  WRITE_SHORT 0x1c 4
			  WRITE_LONG 0x34 spell_level
			  READ_LONG 0x64 abil_offset
			  READ_SHORT 0x68 abil_number
			  READ_BYTE (%abil_offset% + 0x0c) abil_target					
			  READ_SHORT (%abil_offset% + 0x0e) abil_range
			  READ_LONG 0x6a eff_offset
			  WHILE (%abil_number% > 0) BEGIN
				SET abil_number = (%abil_number% - 1)
				WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
			  END
			  LPF DELETE_EFFECT END
			  PATCH_IF (%abil_target% = 4) BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %spell_level% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%real_spell%~ END
				PATCH_IF (%abil_range% < 35) BEGIN
				  PATCH_IF (%abil_range% > 4) BEGIN
					LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
				  END
				  PATCH_IF (%abil_range% < 5) BEGIN
					LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	
				  END
				END
			  END
			  ELSE BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 power = %spell_level% parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%real_spell%~ END
			  END
			  PATCH_IF !(MOD_IS_INSTALLED ~tomeandblood.tp2~ ~62~) BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5src-%spell_level%~ END
			  END
			  PATCH_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~62~) BEGIN
				PATCH_IF (%spell_level% > 1) BEGIN
				  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5src-%spell_level%~ END
				END
			  END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
		  END
// make .EFFs adding the arcane clone
		  CREATE EFF ~%spell_eff%~
			WRITE_LONG 0x10 171
			WRITE_LONG 0x14 1
			WRITE_LONG 0x24 0
			WRITE_LONG 0x28 1
			WRITE_SHORT 0x2c 100
			WRITE_EVALUATED_ASCII 0x30 ~%innate_spell%~ #8
			WRITE_LONG 0x90 1
			WRITE_EVALUATED_ASCII 0x94 ~%spell_eff%~ #8
// make 206 spells preventing the .EFF
		  COPY ~tomeandblood/lib/d5_base.spl~ ~override/%206_spell%.spl~
			WRITE_SHORT 0x1c 4
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
// add 206 spells to CLAB spell
// why isn't d5w206 working with qd_multi??
		  COPY_EXISTING ~d5w206.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
// make learn spells canceling the 206
		  COPY ~tomeandblood/lib/d5_base.spl~ ~override/%learn_spell%.spl~
			WRITE_EVALUATED_ASCII 0x3a ~%spell_icon%~ #8
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%real_spell%~ END
//		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = EVAL ~%real_spell%~ END
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
// make copy of learn spell for kjeron's UI system (eventually, just rename the learn spell to this name)
//		  COPY_EXISTING ~%learn_spell%.spl~ ~override/%spell_res%M.spl~
// add 172 to d5ssplz#
		  COPY_EXISTING ~d5ssplz.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%innate_spell%~ END
// generate slot#x spells
		  COPY_EXISTING ~d5slot%spell_level%a.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  COPY_EXISTING ~d5slot%spell_level%b.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  COPY_EXISTING ~d5slot%spell_level%c.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  COPY_EXISTING ~d5slot%spell_level%d.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
// remove all known spells after chargen
		  COPY_EXISTING ~d50wspl.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%real_spell%~ END
		END // end inner_action
	  END
	END
  END
 END
BUT_ONLY

//set up spell learn UI screens_______________________________________________________
//
INCLUDE ~tomeandblood/lib/sequencer_menu.tpa~

LAF CREATE_SEQUENCER_MENU 
  INT_VAR 
	name = RESOLVE_STR_REF (~Spell Selection~)
	tip = RESOLVE_STR_REF (~Spell Selection~)
	desc = RESOLVE_STR_REF (~This ability allows you to learn new spells~)
  STR_VAR 
	resref = ~d5msorc~
	spelllist = ~d5msorc~
	spelltable = ~QD_SPLSRCKN~
	icon = ~spcl919b~
	title = ~Spell Selection~
	label = ~Select a spell to learn~
	subspell = ~M~
END

COPY_EXISTING ~d5msorc.2da~ ~override/d5msorcX.2da~

COPY ~tomeandblood/data/multi_sorcerers/d5msorc.itm~ ~override~			//	learn spells .itm
  SAY NAME1 @17021
  SAY NAME2 @17021
  SAY UNIDENTIFIED_DESC @17022
  SAY IDENTIFIED_DESC @17022
  LPF ALTER_ITEM_HEADER INT_VAR target = 7 speed = 0 STR_VAR icon = ~spcl919b~ END

COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5msor1.spl~
  SAY NAME1 @17050
  SAY UNIDENTIFIED_DESC @17050
  WRITE_SHORT 0x1c 4
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 location = 4 STR_VAR icon = ~spcl919b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5msorc~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5msor1~ END

APPEND ~d5sorc.2da~ ~LEARNSPLS   GA_D5MSOR1  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~


//remove known spells right after chargen_____________________________________________
//
APPEND ~d5sorc.2da~ ~NO_WSPLS    AP_D50WSPL  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
                                

//apply EFF protections_______________________________________________________________
//
APPEND ~d5sorc.2da~ ~NO_WSPLS    AP_D5W206   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~


//daily spell slot refresh____________________________________________________________
//
COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5slotz.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5slots~ END

APPEND ~d5sorc.2da~ ~SPLSLOTS    AP_D5SLOTZ  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

CREATE EFF ~d5slots~
  WRITE_LONG 0x10 232
  WRITE_LONG 0x14 1
  WRITE_LONG 0x1c 0
  WRITE_LONG 0x20 20
  WRITE_LONG 0x24 9
  WRITE_SHORT 0x2c 100
  WRITE_ASCII 0x30 ~d5sslot~ #8
  WRITE_LONG 0x48 102

COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5sslot.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_value% timing = 1 STR_VAR resource = ~d5srfrsh~ END


// spell to refresh spell slots_______________________________________________________
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5srfrsh.spl~ BEGIN
 COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5srfrsh.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 1 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-3~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-4~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-5~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-6~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-7~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-8~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-9~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
END


/*
//make sure sequencer/contingency works if possible___________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~M_d5meta.lua~ BEGIN
	// umm... actually, maybe the metamagic component will take care of this entirely...h
END
*/


/*
//manually create versions of sequencer/contingency___________________________________
//
COPY ~TomeAndBlood/data/metamagic/spwi420.spl~ ~override/d5sseq1.spl~
	SAY NAME1 @6041
	SAY UNIDENTIFIED_DESC @6042
// only allow to be cast if have 1 each 1st- and 2nd-level slots
// reduce 1st- and 2nd-level slots by 1 when cast

COPY ~TomeAndBlood/data/metamagic/spwi710.spl~ ~override/d5sseq2.spl~
	SAY NAME1 @6043
	SAY UNIDENTIFIED_DESC @6044
// only allow to be cast if have 1 each 2nd/3rd/4th-level slots
// reduce 2nd/3rd/4th-level slots by 1 when cast

COPY ~TomeAndBlood/data/metamagic/spwi809.spl~ ~override/d5sseq3.spl~
	SAY NAME1 @6045
	SAY UNIDENTIFIED_DESC @6046
// only allow to be cast if have 1 each 4th/5th/6th-level slots
// reduce 4th/5th/6th-level slots by 1 when cast
*/


//make sequencer/contingency scrolls unusable by multi sorcerers_______________________
//
ACTION_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~53~) AND !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~54~) BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~scrl9q.itm~ BEGIN
	COPY_EXISTING ~scrl9q.itm~ ~override~
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 parameter1 = %fighter_sorcerer_code% parameter2 = 9 power = 0 timing = 2 END
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 parameter1 = %sorcerer_cleric_code% parameter2 = 9 power = 0 timing = 2 END
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 parameter1 = %sorcerer_thief_code% parameter2 = 9 power = 0 timing = 2 END
  END
END
ACTION_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~53~) AND !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~54~) AND !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~55~) BEGIN
  ACTION_FOR_EACH meta_scroll IN ~scrl6p~ ~scrl8l~ ~scrl9d~ ~scrl7u~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%meta_scroll%.itm~ BEGIN
	  COPY_EXISTING ~%meta_scroll%.itm~ ~override~
		LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 parameter1 = %fighter_sorcerer_code% parameter2 = 9 power = 0 timing = 2 END
		LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 parameter1 = %sorcerer_cleric_code% parameter2 = 9 power = 0 timing = 2 END
		LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 parameter1 = %sorcerer_thief_code% parameter2 = 9 power = 0 timing = 2 END
	END
  END
END

ACTION_IF (MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~55~) BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~M_d5meta.lua~ BEGIN
  	APPEND ~M_d5meta.lua~ ~mageBookStrings['D5W4420'] = mageBookStrings['SPWI420'] -- Minor Sequencer clone, replace resource, keep quotes
mageBookStrings['D5W4617'] = mageBookStrings['SPWI710'] -- Spell Sequencer
mageBookStrings['D5W4710'] = mageBookStrings['SPWI809'] -- Spell Trigger
mageBookStrings['D5W4809'] = mageBookStrings['SPWI617'] -- Contingency
mageBookStrings['D5W4908'] = mageBookStrings['SPWI908'] -- Chain Contingency~
  END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi420d.spl~ BEGIN
  COPY_EXISTING ~spwi420d.spl~ ~override/d5w4420d.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR resource = ~d5w4420~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi420p.spl~ BEGIN
  COPY_EXISTING ~spwi420p.spl~ ~override/d5w4420p.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR resource = ~d5w4420~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi710d.spl~ BEGIN
  COPY_EXISTING ~spwi710d.spl~ ~override/d5w4710d.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR resource = ~d5w4710~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi710p.spl~ BEGIN
  COPY_EXISTING ~spwi710p.spl~ ~override/d5w4710p.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR resource = ~d5w4710~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi809d.spl~ BEGIN
  COPY_EXISTING ~spwi809d.spl~ ~override/d5w4809d.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR resource = ~d5w4809~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi809p.spl~ BEGIN
  COPY_EXISTING ~spwi809p.spl~ ~override/d5w4809p.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR resource = ~d5w4809~ END
END


//multisorc no get innate sequencers__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5adsq1m.spl~ BEGIN
  CREATE SPL ~d5msnsq~
  COPY_EXISTING ~d5msnsq.spl~ ~override~
	LPF ADD_SPELL_HEADER INT_VAR target = 1 END 
  COPY_EXISTING ~d5msnsq.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5adsq1m~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5adsq2m~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5adsq3m~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5adcntm~ END

  APPEND ~d5sorc.2da~ ~NO_META     AP_D5MSNSQ  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
END


//make HLA tables_____________________________________________________________________
// ...clone sorcerer HLAs as innates
//
ACTION_IF FILE_EXISTS_IN_GAME ~spwi920.spl~ BEGIN
  COPY_EXISTING ~spwi920.spl~ ~override/d5hl920.spl~
	WRITE_SHORT 0x1c 4
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi921.spl~ BEGIN
  COPY_EXISTING ~spwi921.spl~ ~override/d5hl921.spl~
	WRITE_SHORT 0x1c 4
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi922.spl~ BEGIN
  COPY_EXISTING ~spwi922.spl~ ~override/d5hl922.spl~
	WRITE_SHORT 0x1c 4
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi923.spl~ BEGIN
  COPY_EXISTING ~spwi923.spl~ ~override/d5hl923.spl~
	WRITE_SHORT 0x1c 4
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi924.spl~ BEGIN
  COPY_EXISTING ~spwi924.spl~ ~override/d5hl924.spl~
	WRITE_SHORT 0x1c 4
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi925.spl~ BEGIN
  COPY_EXISTING ~spwi925.spl~ ~override/d5hl925.spl~
	WRITE_SHORT 0x1c 4
END
ACTION_IF FILE_EXISTS_IN_GAME ~spcl928.spl~ BEGIN
  COPY_EXISTING ~spcl928.spl~ ~override/d5hl928.spl~
	LPF ALTER_EFFECT INT_VAR match_opcode = 42 opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spcl929.spl~ BEGIN
  COPY_EXISTING ~spcl929.spl~ ~override/d5hl929.spl~
	LPF ALTER_EFFECT INT_VAR match_opcode = 42 opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (108 + (0x10000 * 1)) timing = 9 END	
END
ACTION_IF FILE_EXISTS_IN_GAME ~spcl930.spl~ BEGIN
  COPY_EXISTING ~spcl930.spl~ ~override/d5hl930.spl~
	LPF ALTER_EFFECT INT_VAR match_opcode = 42 opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
END

LAF action_replace_hla STR_VAR kit_name = ~D5_FIGHTER_SORCERER~ remove_ability = ~GA_SPWI920~ ability = ~GA_D5HL920~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_FIGHTER_SORCERER~ remove_ability = ~GA_SPWI921~ ability = ~GA_D5HL921~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_FIGHTER_SORCERER~ remove_ability = ~GA_SPWI922~ ability = ~GA_D5HL922~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_FIGHTER_SORCERER~ remove_ability = ~GA_SPWI923~ ability = ~GA_D5HL923~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_FIGHTER_SORCERER~ remove_ability = ~GA_SPWI924~ ability = ~GA_D5HL924~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_FIGHTER_SORCERER~ remove_ability = ~GA_SPWI925~ ability = ~GA_D5HL925~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_FIGHTER_SORCERER~ remove_ability = ~AP_SPWI928~ ability = ~AP_D5HL928~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_FIGHTER_SORCERER~ remove_ability = ~AP_SPWI929~ ability = ~AP_D5HL929~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_FIGHTER_SORCERER~ remove_ability = ~AP_SPWI930~ ability = ~AP_D5HL930~ END

LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_CLERIC~ remove_ability = ~GA_SPWI920~ ability = ~GA_D5HL920~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_CLERIC~ remove_ability = ~GA_SPWI921~ ability = ~GA_D5HL921~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_CLERIC~ remove_ability = ~GA_SPWI922~ ability = ~GA_D5HL922~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_CLERIC~ remove_ability = ~GA_SPWI923~ ability = ~GA_D5HL923~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_CLERIC~ remove_ability = ~GA_SPWI924~ ability = ~GA_D5HL924~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_CLERIC~ remove_ability = ~GA_SPWI925~ ability = ~GA_D5HL925~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_CLERIC~ remove_ability = ~AP_SPWI928~ ability = ~AP_D5HL928~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_CLERIC~ remove_ability = ~AP_SPWI929~ ability = ~AP_D5HL929~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_CLERIC~ remove_ability = ~AP_SPWI930~ ability = ~AP_D5HL930~ END

LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_THIEF~ remove_ability = ~GA_SPWI920~ ability = ~GA_D5HL920~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_THIEF~ remove_ability = ~GA_SPWI921~ ability = ~GA_D5HL921~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_THIEF~ remove_ability = ~GA_SPWI922~ ability = ~GA_D5HL922~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_THIEF~ remove_ability = ~GA_SPWI923~ ability = ~GA_D5HL923~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_THIEF~ remove_ability = ~GA_SPWI924~ ability = ~GA_D5HL924~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_THIEF~ remove_ability = ~GA_SPWI925~ ability = ~GA_D5HL925~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_THIEF~ remove_ability = ~AP_SPWI928~ ability = ~AP_D5HL928~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_THIEF~ remove_ability = ~AP_SPWI929~ ability = ~AP_D5HL929~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_SORCERER_THIEF~ remove_ability = ~AP_SPWI930~ ability = ~AP_D5HL930~ END


//disable quickspell buttons and scroll learning______________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5srcnq.spl~) BEGIN
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5srcnq.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 3 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 4 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 5 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 101 target = 1 parameter2 = 147 timing = 9 END
END

APPEND ~d5sorc.2da~ ~NO_QUICK    AP_D5SRCNQ  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~


//stat-based bonus spells_____________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~qdtnb_attrbon.qd~) BEGIN

  COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols   
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ 
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_CHR_SLOTS~ BEGIN
	    SET chr_slots = %row%
	  END
	END
  BUT_ONLY

  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5nabsw.spl~) BEGIN
	COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5nabsw.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp1~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5absp1~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5abspw~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5abspw~ END
  END

/*
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5absp4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %fighter_sorcerer_code% parameter2 = 9 timing = 9 STR_VAR resource = ~d5abspm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %sorcerer_cleric_code% parameter2 = 9 timing = 9 STR_VAR resource = ~d5abspm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %sorcerer_thief_code% parameter2 = 9 timing = 9 STR_VAR resource = ~d5abspm~ END

  COPY ~TomeAndBlood/data/ability_bonuses/d5_slots.eff~ ~override/d5abspm.eff~
	WRITE_ASCII 0x30 ~d5abspm~ #8

  COPY_EXISTING ~d5absps.spl~ ~override/d5abspm.spl~
	PATCH_FOR_EACH let IN ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ ~u~ ~v~ ~w~ ~x~ ~y~ BEGIN
	  LPF ALTER_EFFECT INT_VAR match_opcode = 326 STR_VAR match_resource = EVAL ~d5chrs%let%~ resource = EVAL ~d5chrm%let%~ END
	END
*/

  APPEND ~d5sorc.2da~  ~STATSLOTS   AP_D5NABSW  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC1   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC1   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC2   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC2   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC3   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC3   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC4   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC4   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC5   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~

  ACTION_DEFINE_ASSOCIATIVE_ARRAY cha_nums_lets BEGIN
	13	=> m
	14	=> n
	15	=> o
	16	=> p
	17	=> q
	18	=> r
	19	=> s
	20	=> t
	21	=> u
	22	=> v
	23	=> w
	24	=> x
	25	=> y
  END

  COPY_EXISTING  ~d5sslot.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 13 parameter2 = 133 timing = 1 STR_VAR resource = ~d5chrml~ END
	PHP_EACH cha_nums_lets AS num => let BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %num% parameter2 = %chr_slots% timing = 1 STR_VAR resource = EVAL ~d5chrm%let%~ END
	END

 ACTION_IF !(FILE_EXISTS_IN_GAME ~d5chrml.spl~) BEGIN
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrml.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrml~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrmm.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrmn.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrmo.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmo~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrmp.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrmq.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrmr.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrms.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrms~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrmt.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrmu.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrmv.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrmw.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrmx.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmx~ END
  COPY ~tomeandblood/lib/d5_base.spl~ ~override/d5chrmy.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmy~ END
 END
 
END
//____________________________________________________________________________________


//make all three clab tables__________________________________________________________
//
/*
COPY_EXISTING ~d5sorc.2da~ ~override/d5fsorc.2da~
COPY_EXISTING ~d5sorc.2da~ ~override/d5csorc.2da~
COPY_EXISTING ~d5sorc.2da~ ~override/d5tsorc.2da~
*/
COPY_EXISTING ~d5fsorc.2da~ ~override~
			  ~d5csorc.2da~ ~override~
			  ~d5tsorc.2da~ ~override~
  APPEND_FILE ~override/d5sorc.2da~


//QD_MULTICLASS_______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5fsorc.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_FIGHTER_SORCERER~ 
		kit_clab = ~d5fsorc~
		base_class = ~M~
		mc_dir = ~tomeandblood/lib/qd_mc~
  END
END 

ACTION_IF FILE_EXISTS_IN_GAME ~d5csorc.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_SORCERER_CLERIC~ 
		kit_clab = ~d5csorc~
		base_class = ~M~
		mc_dir = ~tomeandblood/lib/qd_mc~
  END
END 

ACTION_IF FILE_EXISTS_IN_GAME ~d5tsorc.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_SORCERER_THIEF~ 
		kit_clab = ~d5tsorc~
		base_class = ~M~
		mc_dir = ~tomeandblood/lib/qd_mc~
  END
END 
//__________________________________________________________________________________


//MAKE +SPELL SLOT ITEMS WORK________________________________________________________
//
// make EFFs to increase spontaneous casting slots
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src1e.eff~ BEGIN
  CREATE EFF ~d5src1e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 8)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC1E~ #8
  CREATE EFF ~d5src2e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 12)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC2E~ #8
  CREATE EFF ~d5src3e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 16)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC3E~ #8
  CREATE EFF ~d5src4e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 20)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC4E~ #8
  CREATE EFF ~d5src5e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 8)
	WRITE_LONG 0x20 (108 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC5E~ #8
  CREATE EFF ~d5src6e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 12)
	WRITE_LONG 0x20 (108 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC6E~ #8
  CREATE EFF ~d5src7e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 16)
	WRITE_LONG 0x20 (108 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC7E~ #8
  CREATE EFF ~d5src8e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 20)
	WRITE_LONG 0x20 (108 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC8E~ #8
  CREATE EFF ~d5src9e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 24)
	WRITE_LONG 0x20 (108 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC9E~ #8
  CREATE EFF ~d5src1f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 8)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC1F~ #8
  CREATE EFF ~d5src2f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 12)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC2F~ #8
  CREATE EFF ~d5src3f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 16)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC3F~ #8
  CREATE EFF ~d5src4f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 20)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC4F~ #8
  CREATE EFF ~d5src5f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 8)
	WRITE_LONG 0x20 (108 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC5F~ #8
  CREATE EFF ~d5src6f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 12)
	WRITE_LONG 0x20 (108 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC6F~ #8
  CREATE EFF ~d5src7f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 16)
	WRITE_LONG 0x20 (108 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC7F~ #8
  CREATE EFF ~d5src8f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 20)
	WRITE_LONG 0x20 (108 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC8F~ #8
  CREATE EFF ~d5src9f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 24)
	WRITE_LONG 0x20 (108 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC9F~ #8
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d51l1spl.eff~ BEGIN
// make EFFs to increase traditional mem/cast slots by 1
  CREATE EFF ~d51l1spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 1
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L1SPL~ #8
  CREATE EFF ~d51l2spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 2
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L2SPL~ #8
  CREATE EFF ~d51l3spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 4
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L3SPL~ #8
  CREATE EFF ~d51l4spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 8
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L4SPL~ #8
  CREATE EFF ~d51l5spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 16
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L5SPL~ #8
  CREATE EFF ~d51l6spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 32
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L6SPL~ #8
  CREATE EFF ~d51l7spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 64
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L7SPL~ #8
  CREATE EFF ~d51l8spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 128
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L8SPL~ #8
  CREATE EFF ~d51l9spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 256
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L9SPL~ #8

// make EFFs to increase traditional mem/cast slots by 2
  CREATE EFF ~D52L1spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 1
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L1SPL~ #8
  CREATE EFF ~D52L2spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 2
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L2SPL~ #8
  CREATE EFF ~D52L3spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 4
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L3SPL~ #8
  CREATE EFF ~D52L4spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 8
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L4SPL~ #8
  CREATE EFF ~D52L5spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 16
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L5SPL~ #8
  CREATE EFF ~D52L6spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 32
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L6SPL~ #8
  CREATE EFF ~D52L7spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 64
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L7SPL~ #8
  CREATE EFF ~D52L8spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 128
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L8SPL~ #8
  CREATE EFF ~D52L9spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 256
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L9SPL~ #8

// make EFFs to double traditional mem/cast slots
  CREATE EFF ~D5XL1spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL1SPL~ #8
  CREATE EFF ~D5XL2spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 2
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL2SPL~ #8
  CREATE EFF ~D5XL3spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 3
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL3SPL~ #8
  CREATE EFF ~D5XL4spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 4
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL4SPL~ #8
  CREATE EFF ~D5XL5spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 5
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL5SPL~ #8
  CREATE EFF ~D5XL6spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 6
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL6SPL~ #8
  CREATE EFF ~D5XL7spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 7
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL7SPL~ #8
  CREATE EFF ~D5XL8spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 8
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL8SPL~ #8
  CREATE EFF ~D5XL9spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 9
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL9SPL~ #8

 OUTER_SET mageslot_item_ind = 0
 OUTER_SPRINT $mage_slot_items(~%mageslot_item_ind%~) ~mage_slot_item~
 COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (%SOURCE_SIZE% > 0x72) BEGIN
  	SET plus_slots = 0
	READ_LONG 0x6a effectsoffset ELSE 0
	READ_SHORT 0x70 effectscount ELSE 0
	FOR (effcyc = 0; effcyc < effectscount; effcyc = effcyc + 1) BEGIN
	  READ_SHORT (effectsoffset + (effcyc * 0x30)) opcode ELSE 0
	  PATCH_IF (opcode = 42) BEGIN
		SET plus_slots = 1
	  END
	END
	PATCH_IF (plus_slots = 1) BEGIN
	  SPRINT $mage_slot_items(~%mageslot_item_ind%~) ~%SOURCE_RES%~
	  SET ++mageslot_item_ind
	END
  END
 BUT_ONLY
	  
 ACTION_PHP_EACH mage_slot_items AS ind => slot_item BEGIN
  COPY_EXISTING ~%slot_item%.itm~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 1   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src1e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 2   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src2e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 4   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src3e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 8   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src4e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 16  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src5e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 32  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src6e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 64  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src7e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src8e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src9e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 1   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src1f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 2   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src2f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 4   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src3f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 8   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src4f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 16  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src5f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 32  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src6f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 64  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src7f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src8f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src9f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 0   opcode = 177 parameter1 = 1 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src1f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 0   opcode = 177 parameter1 = 2 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src2f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 3 match_parameter2 = 0   opcode = 177 parameter1 = 3 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src3f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 4 match_parameter2 = 0   opcode = 177 parameter1 = 4 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src4f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 5 match_parameter2 = 0   opcode = 177 parameter1 = 5 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src5f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 6 match_parameter2 = 0   opcode = 177 parameter1 = 6 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src6f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 7 match_parameter2 = 0   opcode = 177 parameter1 = 7 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src7f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 8 match_parameter2 = 0   opcode = 177 parameter1 = 8 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src8f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 9 match_parameter2 = 0   opcode = 177 parameter1 = 9 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src9f~ insert = ~first~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 1   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l1spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 2   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l2spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 4   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l3spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 8   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l4spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 16  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l5spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 32  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l6spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 64  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l7spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l8spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l9spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 1   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l1spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 2   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l2spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 4   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l3spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 8   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l4spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 16  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l5spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 32  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l6spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 64  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l7spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l8spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l9spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl1spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl2spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 3 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl3spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 4 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl4spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 5 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl5spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 6 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl6spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 7 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl7spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 8 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl8spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 9 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl9spl~ END
	LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 202 parameter2 = 115 timing = 2 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
  IF_EXISTS BUT_ONLY
 END

END // end if not already done

END 	//	end define function
//____________________________________________________________________________________

